In [1]:
c = ("keyboard", 98)
c

('keyboard', 98)

In [2]:
type(c)

tuple

In [3]:
import numpy as np
a = np.array([5,5,5,])
a

array([5, 5, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [6]:
b = np.array ([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 1-D Array 

In [7]:
 t = np.zeros(3)
t

array([0., 0., 0.])

In [8]:
p = np.ones(7)
p

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
u = np.empty(3)
u

array([0., 0., 0.])

In [10]:
# with range of elements
f = np.arange(4)
f

array([0, 1, 2, 3])

In [11]:
# with specific range of elements
s = np.arange(4,40)
s

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39])

In [12]:
# continue
y = np.arange(6,60,5)
y

array([ 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56])

In [13]:
# linerly spaced array
h = np.linspace(7,70,num=10)
h

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [14]:
h = np.linspace(5,33, num=12)
h

array([ 5.        ,  7.54545455, 10.09090909, 12.63636364, 15.18181818,
       17.72727273, 20.27272727, 22.81818182, 25.36363636, 27.90909091,
       30.45454545, 33.        ])

In [15]:
# specific data types in array 
m = np.ones(8, dtype=np.int8)
m

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [16]:
n = np.zeros(3, dtype=np.float32)
n

array([0., 0., 0.], dtype=float32)

# 2-D Arrays

In [17]:
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
q = np.ones((5,8))
q

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
w = np.ones((16,32))
w

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

# 3-D Arrays

In [19]:
z = np.arange(24).reshape(2,3,4)
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])